import { Ingredient } from "./form-ingredients.interface";

export const ingredients: Ingredient[] = [
  {
    ingredientId: 1,
    quantity: 0.25,
    name: "Oil Olive",
    unit: "tbsp",
    unitValue: "tbsp",
    isAdded: true,
  },
  {
    ingredientId: 2,
    quantity: 0.5,
    name: "onion, minced",
    unit: "cup",
    unitValue: "cup",
    isAdded: false,
  },
  {
    ingredientId: 3,
    quantity: 1,
    name: "Garlic, Minced",
    unit: "tbsp",
    unitValue: "tbsp",
    isAdded: false,
  },
  {
    ingredientId: 4,
    quantity: 0.5,
    name: "Goody Mushrooms Pieces and Stems",
    unit: "pcs",
    unitValue: "pcs",
    isAdded: false,
  },
  {
    ingredientId: 5,
    quantity: 0.75,
    name: "salt",
    unit: "pcs",
    unitValue: "pcs",
    isAdded: true,
  },
  {
    ingredientId: 6,
    quantity: 0.5,
    name: "small bunch of fresh Spinach",
    unit: "cup",
    unitValue: "cup",
    isAdded: false,
  },
  {
    ingredientId: 7,
    quantity: 1,
    name: "Boiled Chicken, Shreded",
    unit: "cup",
    unitValue: "cup",
    isAdded: false,
  },
  {
    ingredientId: 8,
    quantity: 1,
    name: "Chicken Stock Cubes",
    unit: "pcs",
    unitValue: "pcs",
    isAdded: false,
  },
  {
    ingredientId: 9,
    quantity: 0.75,
    name: "Milk",
    unit: "cup",
    unitValue: "cup",
    isAdded: true,
  },
  {
    ingredientId: 10,
    quantity: 0.125,
    name: "nutmeg",
    unit: "tsp",
    unitValue: "tsp",
    isAdded: false,
  },
  {
    ingredientId: 11,
    quantity: 0.125,
    name: "Flour",
    unit: "cup",
    unitValue: "cup",
    isAdded: false,
  },
  {
    ingredientId: 12,
    quantity: 0.25,
    name: "Parmesan Cheese, Grated",
    unit: "cup",
    unitValue: "cup",
    isAdded: false,
  },
];

export const ModelFormIngredients = {
  ingredients,
  servingSize: 2,
  labelAdd: "Add",
  labelAdded: "Added",
  textIngredients: "Ingredients",
  textAddIngredientsToShoppingList: "Add Ingredients to Shopping List",
  textServingSize: "Serving Size",
  textAddAllToShoppingList: "Add All to Shopping List",
};
