import { UserMenuProps } from "./user-menu.interface";

export const ModelUserMenu: UserMenuProps = {
  isAuth: false,
  userAvatar: "",
  userAvatarSVGName: "JD",
  myProfileLabel: "My Profile",
  myProfileURL: "#",
  notificationLabel: "Notification",
  notificationURL: "#",
  shoppingListLabel: "Shopping List",
  shoppingListURL: "#",
  saveForLaterLabel: "Favorites",
  saveForLaterURL: "#",
  mealPlannerLabel: "Meal Planner",
  mealPlannerURL: "#",
  accountSettingsLabel: "Account Settings",
  accountSettingsURL: "#",
  helpLabel: "Help",
  helpURL: "#",
  loginLabel: "Login",
  loginURL: "#",
  registerLabel: "Register",
  registerLoginLabel: "Register / Login",
  registerURL: "#",
  logoutLabel: "Logout",
  logoutURL: "#",
};
